In [1]:
from neuralnetlib.preprocessing import pad_sequences, clip_gradients, normalize_gradient, cosine_similarity, StandardScaler, MinMaxScaler, Imputer
from neuralnetlib.utils import train_test_split

import numpy as np

## Pad Sequences

In [2]:
sequences = [
    [1, 2, 3],
    [4, 5],
    [6, 7, 8, 9],
    [0]
]

max_len = 5
padded_sequences = pad_sequences(sequences, max_length=max_len, padding='post', truncating='post', pad_value=0)

# Affichage des résultats
print("Séquences d'origine:")
for seq in sequences:
    print(seq)

print("\nSéquences après padding:")
for seq in padded_sequences:
    print(seq)

Séquences d'origine:
[1, 2, 3]
[4, 5]
[6, 7, 8, 9]
[0]

Séquences après padding:
[1 2 3 0 0]
[4 5 0 0 0]
[6 7 8 9 0]
[0 0 0 0 0]


## Clip & Normalize gradients

In [3]:
gradients = np.array([3.0, 14.0, 0.0])

threshold = 5.0
clipped_gradients = clip_gradients(gradients, threshold=threshold)

scale = 1.0
normalized_gradients = normalize_gradient(gradients, scale=scale)

print("Original gradients:", gradients)
print(f"Clipped gradients (threshold={threshold}):", clipped_gradients)
print(f"Normalized gradients (scale={scale}):", normalized_gradients)

Original gradients: [ 3. 14.  0.]
Clipped gradients (threshold=5.0): [1.04764544 4.88901207 0.        ]
Normalized gradients (scale=1.0): [0.20952909 0.97780241 0.        ]


## Cosine Similarity

In [4]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
vector3 = np.array([0, 0, 0])

similarity1 = cosine_similarity(vector1, vector2)
similarity2 = cosine_similarity(vector1, vector3)

print("Cosine similarity between vector1 and vector2:", similarity1)
print("Cosine similarity between vector1 and vector3:", similarity2)

Cosine similarity between vector1 and vector2: 0.9746318461970762
Cosine similarity between vector1 and vector3: 0.0


## Standard & Min-Max Scalers

In [5]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Original Data:")
print(data)

scaler_standard = StandardScaler()
data_standard = scaler_standard.fit_transform(data)
print("\nStandard Scaled Data:")
print(data_standard)

scaler_minmax = MinMaxScaler(feature_range=(0, 1))
data_minmax = scaler_minmax.fit_transform(data)
print("\nMinMax Scaled Data:")
print(data_minmax)

Original Data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Standard Scaled Data:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]

MinMax Scaled Data:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


## Train test split

In [6]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

print("x:", x)
print("y:", y)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
print("\nx_train:", x_train)
print("x_test:", x_test)
print("y_train:", y_train)
print("y_test:", y_test)

x_train, x_test = train_test_split(x, test_size=0.3, random_state=42)
print("\nx_train:", x_train)
print("x_test:", x_test)

x: [ 1  2  3  4  5  6  7  8  9 10]
y: [0 1 0 1 0 1 0 1 0 1]

x_train: [6 7 1 8 4 3 5]
x_test: [10  2  9]
y_train: [1 0 0 1 1 0 0]
y_test: [1 1 0]

x_train: [6 7 1 8 4 3 5]
x_test: [10  2  9]


## Imputer

In [8]:
strategies = ["mean", "median", "mode", "constant", "random"]

print("Original Data:")
print(data)

for strategy in strategies:
    print(f"\nTesting strategy: {strategy}")
    
    if strategy == "constant":
        imputer = Imputer(strategy=strategy, fill_value=0)
    else:
        imputer = Imputer(strategy=strategy, random_state=42)
    
    imputer.fit(data)
    transformed_data = imputer.transform(data)
    
    print("Imputed Data:")
    print(transformed_data)

data_1d = np.array([1.0, np.nan, 3.0, np.nan, 5.0])
imputer = Imputer(strategy="mean")
print("\nOriginal 1D Data:", data_1d)
transformed_1d = imputer.fit_transform(data_1d)
print("Imputed 1D Data:", transformed_1d)

imputer_with_indicator = Imputer(strategy="mean", add_indicator=True)
imputer_with_indicator.fit(data)
transformed_with_indicators = imputer_with_indicator.transform(data)
print("\nImputed Data with Missing Indicators:")
print(transformed_with_indicators)

data = np.array([
    [1.0, np.nan, 3.0],
    [np.nan, 2.0, 4.0],
    [5.0, 6.0, np.nan]
])

imputer = Imputer(strategy="mean", add_indicator=True)

imputed_data = imputer.fit_transform(data)

print("\nImputed data (with indicators):")
print(imputed_data)

Original Data:
[[ 1. nan  3.]
 [nan  2.  4.]
 [ 5.  6. nan]]

Testing strategy: mean
Imputed Data:
[[1.  4.  3. ]
 [3.  2.  4. ]
 [5.  6.  3.5]]

Testing strategy: median
Imputed Data:
[[1.  4.  3. ]
 [3.  2.  4. ]
 [5.  6.  3.5]]

Testing strategy: mode
Imputed Data:
[[1. 2. 3.]
 [1. 2. 4.]
 [5. 6. 3.]]

Testing strategy: constant
Imputed Data:
[[1. 0. 3.]
 [0. 2. 4.]
 [5. 6. 0.]]

Testing strategy: random
Imputed Data:
[[1. 2. 3.]
 [1. 2. 4.]
 [5. 6. 3.]]

Original 1D Data: [ 1. nan  3. nan  5.]
Imputed 1D Data: [1. 3. 3. 3. 5.]

Imputed Data with Missing Indicators:
[[1.  4.  3.  0.  1.  0. ]
 [3.  2.  4.  1.  0.  0. ]
 [5.  6.  3.5 0.  0.  1. ]]

Imputed data (with indicators):
[[1.  4.  3.  0.  1.  0. ]
 [3.  2.  4.  1.  0.  0. ]
 [5.  6.  3.5 0.  0.  1. ]]
