# MNIST Loading Saved Model

## Imports

In [1]:
from tensorflow.keras.datasets import mnist  # Dataset for testing

from neuralnetlib.model import Model
from neuralnetlib.preprocessing import one_hot_encode
from neuralnetlib.utils import train_test_split
from neuralnetlib.metrics import accuracy_score, confusion_matrix

## 1. Loading the MNIST dataset

In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

## 2. Preprocessing

In [3]:
x_train = x_train.reshape(-1, 28 * 28) / 255.0
x_test = x_test.reshape(-1, 28 * 28) / 255.0
y_train = one_hot_encode(y_train, num_classes=10)
y_test = one_hot_encode(y_test, num_classes=10)

## 3. Split the training data into training and validation sets

In [4]:
_, x_val, _, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

## 4. Load the model

In [5]:
model = Model.load('my_mnist_model.npz')

## 5. Predict and evaluate on the validation set

In [6]:
y_pred_val = model.predict(x_val)
accuracy_val = accuracy_score(y_pred_val, y_val)
print(f'Validation Accuracy: {accuracy_val}')

Validation Accuracy: 0.9728333333333333


## 6. Optionally, you can still evaluate on the test set

In [7]:
y_pred_test = model.predict(x_test)
accuracy_test = accuracy_score(y_pred_test, y_test)
print(f'Test Accuracy: {accuracy_test}')
print(f'Confusion Matrix:\n{confusion_matrix(y_pred_test, y_test)}')

Test Accuracy: 0.9567
Confusion Matrix:
[[ 963    0    1    2    2    1    4    1    3    3]
 [   0 1119    2    3    0    1    1    2    6    1]
 [   5    3  990    8    3    1    4   10    8    0]
 [   1    2    5  966    1   19    1    6    4    5]
 [   1    1    2    0  932    1    8    0    4   33]
 [   7    0    1   15    2  852    5    1    6    3]
 [   4    5    2    3    5   14  921    0    4    0]
 [   0    9   17    5    6    0    0  969    2   20]
 [   8    1    7   20    3   11    8    3  899   14]
 [   3    2    1   10   18    9    0    8    2  956]]
