# MNIST Loading Saved Model

## Imports

In [1]:
from tensorflow.keras.datasets import mnist  # Dataset for testing

from neuralnetlib.model import Model
from neuralnetlib.preprocessing import one_hot_encode
from neuralnetlib.utils import train_test_split
from neuralnetlib.metrics import accuracy_score, confusion_matrix

## 1. Loading the MNIST dataset

In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

## 2. Preprocessing

In [3]:
x_train = x_train.reshape(-1, 28 * 28) / 255.0
x_test = x_test.reshape(-1, 28 * 28) / 255.0
y_train = one_hot_encode(y_train, num_classes=10)
y_test = one_hot_encode(y_test, num_classes=10)

## 3. Split the training data into training and validation sets

In [4]:
_, x_val, _, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

## 4. Load the model

In [5]:
model = Model.load('my_mnist_model.npz')

## 5. Predict and evaluate on the validation set

In [6]:
y_pred_val = model.predict(x_val)
accuracy_val = accuracy_score(y_pred_val, y_val)
print(f'Validation Accuracy: {accuracy_val}')

Validation Accuracy: 0.899


## 6. Optionally, you can still evaluate on the test set

In [7]:
y_pred_test = model.predict(x_test)
accuracy_test = accuracy_score(y_pred_test, y_test)
print(f'Test Accuracy: {accuracy_test}')
print(f'Confusion Matrix:\n{confusion_matrix(y_pred_test, y_test)}')

Test Accuracy: 0.8863
Confusion Matrix:
[[ 937    0    0    1   11    7    2   18    1    3]
 [   0 1097    3    4    0    3    2    4   19    3]
 [  13    9  858   36   26    1   23   38   16   12]
 [   8    6   18  899    2   33    2   16   12   14]
 [   1    0    1    0  944    0    7    2    1   26]
 [  19    0    0   82   30  701   12    5   23   20]
 [  18    2    0    0   70   15  849    1    2    1]
 [   0    9   10    5   15    0    0  945    4   40]
 [   6   22    3    3   37   26    9    2  803   63]
 [   3    2    1   11  137    2    0   15    8  830]]
