# MNIST Loading Saved Model

## Imports

In [1]:
from tensorflow.keras.datasets import mnist  # Dataset for testing

from neuralnetlib.model import Model
from neuralnetlib.preprocessing import one_hot_encode
from neuralnetlib.utils import train_test_split
from neuralnetlib.metrics import accuracy_score, confusion_matrix

## 1. Loading the MNIST dataset

In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

## 2. Preprocessing

In [3]:
x_train = x_train.reshape(-1, 28 * 28) / 255.0
x_test = x_test.reshape(-1, 28 * 28) / 255.0
y_train = one_hot_encode(y_train, num_classes=10)
y_test = one_hot_encode(y_test, num_classes=10)

## 3. Split the training data into training and validation sets

In [4]:
_, x_val, _, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

## 4. Load the model

In [5]:
model = Model.load('my_mnist_model.npz')

## 5. Predict and evaluate on the validation set

In [6]:
y_pred_val = model.predict(x_val)
accuracy_val = accuracy_score(y_pred_val, y_val)
print(f'Validation Accuracy: {accuracy_val}')

Validation Accuracy: 0.9738333333333333


## 6. Optionally, you can still evaluate on the test set

In [7]:
y_pred_test = model.predict(x_test)
accuracy_test = accuracy_score(y_pred_test, y_test)
print(f'Test Accuracy: {accuracy_test}')
print(f'Confusion Matrix:\n{confusion_matrix(y_pred_test, y_test)}')

Test Accuracy: 0.9549
Confusion Matrix:
[[ 958    0    3    0    0    3    7    2    4    3]
 [   0 1117    1    6    0    1    1    2    6    1]
 [   5    1  983   11    3    0    4   16    9    0]
 [   2    0   10  959    0   13    1    7    8   10]
 [   2    1    6    0  909    0    6    0    0   58]
 [   9    1    0   20    0  838    8    2    3   11]
 [  10    4    4    1    5    6  917    0   10    1]
 [   1    8   10    6    0    0    0  982    0   21]
 [   5    3    9    7    4    6    5    7  917   11]
 [   3    5    3    5   10    4    2    7    1  969]]
