# MNIST Loading Saved Sequential

## Imports

In [1]:
from tensorflow.keras.datasets import mnist  # Dataset for testing

from neuralnetlib.models import Sequential
from neuralnetlib.utils import train_test_split
from neuralnetlib.preprocessing import one_hot_encode
from neuralnetlib.metrics import accuracy_score, confusion_matrix

## 1. Loading the MNIST dataset

In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

## 2. Preprocessing

In [3]:
x_train = x_train.reshape(-1, 28 * 28) / 255.0
x_test = x_test.reshape(-1, 28 * 28) / 255.0
y_train = one_hot_encode(y_train, num_classes=10)
y_test = one_hot_encode(y_test, num_classes=10)

## 3. Split the training data into training and validation sets

In [4]:
_, x_val, _, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

## 4. Load the model

In [5]:
model = Sequential.load('my_mnist_model.npz')

## 5. Predict and evaluate on the validation set

In [6]:
y_pred_val = model.predict(x_val)
accuracy_val = accuracy_score(y_pred_val, y_val)
print(f'Validation Accuracy: {accuracy_val}')

Validation Accuracy: 0.9619166666666666


## 6. Optionally, you can still evaluate on the test set

In [7]:
y_pred_test = model.predict(x_test)
accuracy_test = accuracy_score(y_pred_test, y_test)
print(f'Test Accuracy: {accuracy_test}')
print(f'Confusion Matrix:\n{confusion_matrix(y_pred_test, y_test)}')

Test Accuracy: 0.9524
Confusion Matrix:
[[ 966    0    1    1    1    6    1    2    2    0]
 [   0 1122    4    1    0    0    1    2    5    0]
 [   7    2  981    8    4    0    7   12    8    3]
 [   2    2    7  963    0    6    0   13   12    5]
 [   2    3    7    0  904    0    7    4    3   52]
 [   5    7    1   26    3  824    2    4   11    9]
 [  11    5    7    1    9   16  907    0    2    0]
 [   2    8   17    4    4    0    0  981    1   11]
 [   3    4    6   15    4    9    6    7  910   10]
 [   6    4    0    9    7    3    0    8    6  966]]
